### PR TITLE
Redis broker url added to cueo-backend environment

### PR DESCRIPTION
**Pull request by PraveenCuebook**

### CODE REVIEW

**Comment by ArunMu21** [comment]
Hello @PraveenCuebook, I am facing " ERROR Connection to Redis lost: Retry (9/20) in 1.00 second." issue. Will this PR changes resolves this?

**Comment by PraveenCuebook** [comment]
Yes, Once this PR is closed .

**Comment by PraveenCuebook** [comment]
@ArunMu21  Once this PR is closed this issue will be solved. Error has reproduced.

**Comment by ArunMu21** [comment]
I see there is only one change has been done..I did the same changes in my file...still getting the same issue

**Comment by PraveenCuebook** [comment]
@ArunMu21 Working on it. It was just one part.

**Comment by PraveenCuebook** [comment]
@ArunMu21  These changes will fix "Connection to Redis lost: Retry (19/20) in 1.00 second"

**Review by vincue — APPROVED** [review]

**Comment by Bowen0729** [comment]
@PraveenCuebook got it!
but the image in docker hub haven't been updated, if user fllow the doc to install the cueobserve, there still this problem

**Pull request merged**
